### ISSUE TITLE
award_countries.py is broken

### ISSUE THREAD

**Issue by JohnSmithDev** [JohnSmithDev/ISFDB-Tools#14]
isfdb_tools $ ./award_countries.py -w clark -y 2015
Traceback (most recent call last):
  File "./award_countries.py", line 87, in <module>
    conn, args, level_filter)
  File "./award_countries.py", line 55, in get_award_countries
    val = get_author_country( conn, author_filter_args, overrides=True)
  File "/proj/isfdb_tools/author_country.py", line 73, in get_author_country
    return overrides[filter_args.exact_author]
TypeError: unhashable type: 'list'

Not sure if this is a recent regression and/or an invocation that the script isn't expecting, but it shouldn't do this

**Comment by JohnSmithDev** [comment]
Gah - I just committed a fix for this, but put the wrong issue number in the commit message
