### ISSUE TITLE
author_country TypeError: Connection.execute() got an unexpected keyword argument 'author'

### ISSUE THREAD

**Issue by RichardScottOZ** [JohnSmithDev/ISFDB-Tools#18]
Hi John,

Any idea what might be going on here? Some quirk of my database connection method?

ISFDB_CONNECTION_DETAILS=mysql+mysqlconnector://rscott_isfdb:password@localhost:3306/isfdb ./author_country.py -a "Stephen Baxter" -

```python
 ./author_country.py -a "Stephen Baxter"
Traceback (most recent call last):
  File "/home/rscott/GIT/ISFDB-Tools/./author_country.py", line 141, in <module>
    print(get_author_country(conn, args, overrides=overrides))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rscott/GIT/ISFDB-Tools/./author_country.py", line 94, in get_author_country
    results = conn.execute(query, **params).fetchall()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Connection.execute() got an unexpected keyword argument 'author'
```

**Comment by JohnSmithDev** [comment]
Blimey, someone else has actually tried to use this code, so I didn't completely waste my time!  Thanks for being the first ;-)

The "good" news is that I get the same error here, so hopefully I can work out what I screwed up and push out a fix.  Looks like that module doesn't have any test coverage either, so an ideal opportunity for me to do something that should have been done properly in the first place.

Unfortunately, I'm a bit busy at the mo' with Hugo/Worldcon related stuff (look or posts by the account ErsatzCulture on Twitter/Mastodon/BlueSky if you're interested in that drama), so whilst the fix is hopefully simple, I dunno when I might get round to do it; hopefully in the next few days.

Sorry for the inconvenience, and thanks again for using this, or at least trying to!

**Comment by RichardScottOZ** [comment]
No worries!  No rush at alll.  I'll check out the drama as you suggest. :)

I was thinking of doing a bunch of this myself, so you have saved me a LOT of time.

**Comment by RichardScottOZ** [comment]
I ran a couple of others at random the other day that seemed to work.
